### PR TITLE
Bookings index

### PR DESCRIPTION
**Pull request by aallamand**
Added partials on the index view that :
1. Display the bookings made by a user
2. Display the bookings made on a car

The display is conditionnal. 

I also needed to change some methods to reuse them : 
- email_owner
- email_renter
- total
I have adapted the show view to avoid bugs. 

Finally I have defined some methods as helpers at the bottom of the controller to allow uses in views. 

Please review this US :-)
@clemfrnt @jaimethibault @dayanazia

### CODE REVIEW

**Comment by aallamand** [comment]
@clemfrnt @jaimethibault @dayanazia s'il vous plait.....
Faites ma code review....

**Comment by clemfrnt** [comment]
my bookins dans nabar stp

**Comment by clemfrnt** [comment]
tables of owner ducplicating

**Comment by clemfrnt** [comment]
Pourquoi pas en titre  "My next Pimped Cars" ou "My future rental" ? 
et pour le owner : "My cars booked" ? 
A discuter demain matin ?

**Comment by aallamand** [comment]
Yo, 

I have filtered the bookings index view by cars and corrected the links in the navbar. 

@clemfrnt @jaimethibault @dayanazia  Can you review the branch please ?

**Pull request merged**
